// Copies ABIs from contracts/out and the deployment manifest into src/lib/generated.
// Run after `forge build` / `npm run deploy:local`:  npm run abi:sync
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "contracts/out");
const gen = resolve(root, "src/lib/generated");
mkdirSync(gen, { recursive: true });

const CONTRACTS = ["IndexVault", "IndexToken", "IndexFactory", "MockOracle", "MockERC20", "MockSwapExecutor"];

let abis = "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit.\n";
for (const name of CONTRACTS) {
  const file = resolve(out, `${name}.sol/${name}.json`);
  if (!existsSync(file)) {
    console.error(`missing ${file} — run \`forge build\` in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(file, "utf8"));
  abis += `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(resolve(gen, "abis.ts"), abis);
console.log(`wrote src/lib/generated/abis.ts (${CONTRACTS.length} ABIs)`);

// Which manifest gets baked into the build: DEPLOYMENT=local (default) | production | <name>.
const target = process.env.DEPLOYMENT ?? "local";
const depFile = resolve(root, `contracts/deployments/${target}.json`);
const dep = existsSync(depFile) ? JSON.parse(readFileSync(depFile, "utf8")) : null;
const body = dep
  ? `export const localDeployment = ${JSON.stringify(dep, null, 2)} as const;\n`
  : `export const localDeployment = null;\n`;
writeFileSync(
  resolve(gen, "deployments.ts"),
  "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit.\n" + body,
);
console.log(
  dep
    ? `wrote src/lib/generated/deployments.ts from contracts/deployments/${target}.json`
    : `no deployments/${target}.json — wrote null deployment`,
);
